/*
 * This file is generated by jOOQ.
 */
package com.technokratos.model.jooq.tables;


import com.technokratos.model.jooq.Keys;
import com.technokratos.model.jooq.Public;
import com.technokratos.model.jooq.tables.records.PublicationVideoRecord;

import java.util.Arrays;
import java.util.List;
import java.util.UUID;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row4;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PublicationVideo extends TableImpl<PublicationVideoRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.publication_video</code>
     */
    public static final PublicationVideo PUBLICATION_VIDEO_ENTITY = new PublicationVideo();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<PublicationVideoRecord> getRecordType() {
        return PublicationVideoRecord.class;
    }

    /**
     * The column <code>public.publication_video.id</code>.
     */
    public final TableField<PublicationVideoRecord, UUID> ID = createField(DSL.name("id"), SQLDataType.UUID.nullable(false).defaultValue(DSL.field("uuid_generate_v4()", SQLDataType.UUID)), this, "");

    /**
     * The column <code>public.publication_video.extension</code>.
     */
    public final TableField<PublicationVideoRecord, String> EXTENSION = createField(DSL.name("extension"), SQLDataType.VARCHAR(16).nullable(false), this, "");

    /**
     * The column <code>public.publication_video.size</code>.
     */
    public final TableField<PublicationVideoRecord, Long> SIZE = createField(DSL.name("size"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.publication_video.publication_id</code>.
     */
    public final TableField<PublicationVideoRecord, UUID> PUBLICATION_ID = createField(DSL.name("publication_id"), SQLDataType.UUID, this, "");

    private PublicationVideo(Name alias, Table<PublicationVideoRecord> aliased) {
        this(alias, aliased, null);
    }

    private PublicationVideo(Name alias, Table<PublicationVideoRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.publication_video</code> table reference
     */
    public PublicationVideo(String alias) {
        this(DSL.name(alias), PUBLICATION_VIDEO_ENTITY);
    }

    /**
     * Create an aliased <code>public.publication_video</code> table reference
     */
    public PublicationVideo(Name alias) {
        this(alias, PUBLICATION_VIDEO_ENTITY);
    }

    /**
     * Create a <code>public.publication_video</code> table reference
     */
    public PublicationVideo() {
        this(DSL.name("publication_video"), null);
    }

    public <O extends Record> PublicationVideo(Table<O> child, ForeignKey<O, PublicationVideoRecord> key) {
        super(child, key, PUBLICATION_VIDEO_ENTITY);
    }

    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    @Override
    public UniqueKey<PublicationVideoRecord> getPrimaryKey() {
        return Keys.PUBLICATION_VIDEO_PKEY;
    }

    @Override
    public List<UniqueKey<PublicationVideoRecord>> getKeys() {
        return Arrays.<UniqueKey<PublicationVideoRecord>>asList(Keys.PUBLICATION_VIDEO_PKEY);
    }

    @Override
    public List<ForeignKey<PublicationVideoRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<PublicationVideoRecord, ?>>asList(Keys.PUBLICATION_VIDEO__PUBLICATION_VIDEO_PUBLICATION_ID_FKEY);
    }

    private transient Publication _publication;

    public Publication publication() {
        if (_publication == null)
            _publication = new Publication(this, Keys.PUBLICATION_VIDEO__PUBLICATION_VIDEO_PUBLICATION_ID_FKEY);

        return _publication;
    }

    @Override
    public PublicationVideo as(String alias) {
        return new PublicationVideo(DSL.name(alias), this);
    }

    @Override
    public PublicationVideo as(Name alias) {
        return new PublicationVideo(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public PublicationVideo rename(String name) {
        return new PublicationVideo(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public PublicationVideo rename(Name name) {
        return new PublicationVideo(name, null);
    }

    // -------------------------------------------------------------------------
    // Row4 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row4<UUID, String, Long, UUID> fieldsRow() {
        return (Row4) super.fieldsRow();
    }
}
