/*
 * This file is generated by jOOQ.
 */
package com.technokratos.model.jooq.tables.pojos;


import lombok.Builder;
import lombok.EqualsAndHashCode;

import java.io.Serializable;
import java.util.UUID;


/**
 * This class is generated by jOOQ.
 */
@Builder
@EqualsAndHashCode
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AccountImageEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    private UUID   id;
    private String extension;
    private Long   size;
    private UUID   accountId;

    public AccountImageEntity() {}

    public AccountImageEntity(AccountImageEntity value) {
        this.id = value.id;
        this.extension = value.extension;
        this.size = value.size;
        this.accountId = value.accountId;
    }

    public AccountImageEntity(
        UUID   id,
        String extension,
        Long   size,
        UUID   accountId
    ) {
        this.id = id;
        this.extension = extension;
        this.size = size;
        this.accountId = accountId;
    }

    /**
     * Getter for <code>public.account_image.id</code>.
     */
    public UUID getId() {
        return this.id;
    }

    /**
     * Setter for <code>public.account_image.id</code>.
     */
    public void setId(UUID id) {
        this.id = id;
    }

    /**
     * Getter for <code>public.account_image.extension</code>.
     */
    public String getExtension() {
        return this.extension;
    }

    /**
     * Setter for <code>public.account_image.extension</code>.
     */
    public void setExtension(String extension) {
        this.extension = extension;
    }

    /**
     * Getter for <code>public.account_image.size</code>.
     */
    public Long getSize() {
        return this.size;
    }

    /**
     * Setter for <code>public.account_image.size</code>.
     */
    public void setSize(Long size) {
        this.size = size;
    }

    /**
     * Getter for <code>public.account_image.account_id</code>.
     */
    public UUID getAccountId() {
        return this.accountId;
    }

    /**
     * Setter for <code>public.account_image.account_id</code>.
     */
    public void setAccountId(UUID accountId) {
        this.accountId = accountId;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("AccountImageEntity (");

        sb.append(id);
        sb.append(", ").append(extension);
        sb.append(", ").append(size);
        sb.append(", ").append(accountId);

        sb.append(")");
        return sb.toString();
    }
}
