/*
 * This file is generated by jOOQ.
 */
package com.technokratos.model.jooq.tables.pojos;


import com.technokratos.model.jooq.enums.AccountRole;
import com.technokratos.model.jooq.enums.AccountState;
import com.technokratos.model.jooq.enums.Gender;
import lombok.Builder;
import lombok.EqualsAndHashCode;

import java.io.Serializable;
import java.time.LocalDateTime;
import java.util.UUID;


/**
 * This class is generated by jOOQ.
 */
@Builder
@EqualsAndHashCode
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AccountEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    private UUID          id;
    private String        email;
    private String        hashPassword;
    private String        username;
    private AccountState  state;
    private AccountRole   role;
    private String        firstName;
    private String        lastName;
    private Gender        gender;
    private String        aboutMe;
    private LocalDateTime birthDate;
    private LocalDateTime createdDate;
    private LocalDateTime updatedDate;

    public AccountEntity() {}

    public AccountEntity(AccountEntity value) {
        this.id = value.id;
        this.email = value.email;
        this.hashPassword = value.hashPassword;
        this.username = value.username;
        this.state = value.state;
        this.role = value.role;
        this.firstName = value.firstName;
        this.lastName = value.lastName;
        this.gender = value.gender;
        this.aboutMe = value.aboutMe;
        this.birthDate = value.birthDate;
        this.createdDate = value.createdDate;
        this.updatedDate = value.updatedDate;
    }

    public AccountEntity(
        UUID          id,
        String        email,
        String        hashPassword,
        String        username,
        AccountState  state,
        AccountRole   role,
        String        firstName,
        String        lastName,
        Gender        gender,
        String        aboutMe,
        LocalDateTime birthDate,
        LocalDateTime createdDate,
        LocalDateTime updatedDate
    ) {
        this.id = id;
        this.email = email;
        this.hashPassword = hashPassword;
        this.username = username;
        this.state = state;
        this.role = role;
        this.firstName = firstName;
        this.lastName = lastName;
        this.gender = gender;
        this.aboutMe = aboutMe;
        this.birthDate = birthDate;
        this.createdDate = createdDate;
        this.updatedDate = updatedDate;
    }

    public boolean isConfirmed() {
        return state == AccountState.CONFIRMED;
    }

    public boolean isBanned() {
        return state == AccountState.BANNED;
    }

    public boolean isDeleted() {
        return state == AccountState.DELETED;
    }

    /**
     * Getter for <code>public.account.id</code>.
     */
    public UUID getId() {
        return this.id;
    }

    /**
     * Setter for <code>public.account.id</code>.
     */
    public void setId(UUID id) {
        this.id = id;
    }

    /**
     * Getter for <code>public.account.email</code>.
     */
    public String getEmail() {
        return this.email;
    }

    /**
     * Setter for <code>public.account.email</code>.
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * Getter for <code>public.account.hash_password</code>.
     */
    public String getHashPassword() {
        return this.hashPassword;
    }

    /**
     * Setter for <code>public.account.hash_password</code>.
     */
    public void setHashPassword(String hashPassword) {
        this.hashPassword = hashPassword;
    }

    /**
     * Getter for <code>public.account.username</code>.
     */
    public String getUsername() {
        return this.username;
    }

    /**
     * Setter for <code>public.account.username</code>.
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * Getter for <code>public.account.state</code>.
     */
    public AccountState getState() {
        return this.state;
    }

    /**
     * Setter for <code>public.account.state</code>.
     */
    public void setState(AccountState state) {
        this.state = state;
    }

    /**
     * Getter for <code>public.account.role</code>.
     */
    public AccountRole getRole() {
        return this.role;
    }

    /**
     * Setter for <code>public.account.role</code>.
     */
    public void setRole(AccountRole role) {
        this.role = role;
    }

    /**
     * Getter for <code>public.account.first_name</code>.
     */
    public String getFirstName() {
        return this.firstName;
    }

    /**
     * Setter for <code>public.account.first_name</code>.
     */
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    /**
     * Getter for <code>public.account.last_name</code>.
     */
    public String getLastName() {
        return this.lastName;
    }

    /**
     * Setter for <code>public.account.last_name</code>.
     */
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    /**
     * Getter for <code>public.account.gender</code>.
     */
    public Gender getGender() {
        return this.gender;
    }

    /**
     * Setter for <code>public.account.gender</code>.
     */
    public void setGender(Gender gender) {
        this.gender = gender;
    }

    /**
     * Getter for <code>public.account.about_me</code>.
     */
    public String getAboutMe() {
        return this.aboutMe;
    }

    /**
     * Setter for <code>public.account.about_me</code>.
     */
    public void setAboutMe(String aboutMe) {
        this.aboutMe = aboutMe;
    }

    /**
     * Getter for <code>public.account.birth_date</code>.
     */
    public LocalDateTime getBirthDate() {
        return this.birthDate;
    }

    /**
     * Setter for <code>public.account.birth_date</code>.
     */
    public void setBirthDate(LocalDateTime birthDate) {
        this.birthDate = birthDate;
    }

    /**
     * Getter for <code>public.account.created_date</code>.
     */
    public LocalDateTime getCreatedDate() {
        return this.createdDate;
    }

    /**
     * Setter for <code>public.account.created_date</code>.
     */
    public void setCreatedDate(LocalDateTime createdDate) {
        this.createdDate = createdDate;
    }

    /**
     * Getter for <code>public.account.updated_date</code>.
     */
    public LocalDateTime getUpdatedDate() {
        return this.updatedDate;
    }

    /**
     * Setter for <code>public.account.updated_date</code>.
     */
    public void setUpdatedDate(LocalDateTime updatedDate) {
        this.updatedDate = updatedDate;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("AccountEntity (");

        sb.append(id);
        sb.append(", ").append(email);
        sb.append(", ").append(hashPassword);
        sb.append(", ").append(username);
        sb.append(", ").append(state);
        sb.append(", ").append(role);
        sb.append(", ").append(firstName);
        sb.append(", ").append(lastName);
        sb.append(", ").append(gender);
        sb.append(", ").append(aboutMe);
        sb.append(", ").append(birthDate);
        sb.append(", ").append(createdDate);
        sb.append(", ").append(updatedDate);

        sb.append(")");
        return sb.toString();
    }
}
