/*
 * This file is generated by jOOQ.
 */
package com.technokratos.model.jooq.tables.pojos;


import lombok.Builder;
import lombok.EqualsAndHashCode;

import java.io.Serializable;
import java.util.UUID;


/**
 * This class is generated by jOOQ.
 */
@Builder
@EqualsAndHashCode
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PublicationVideoEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    private UUID   id;
    private String extension;
    private Long   size;
    private UUID   publicationId;

    public PublicationVideoEntity() {}

    public PublicationVideoEntity(PublicationVideoEntity value) {
        this.id = value.id;
        this.extension = value.extension;
        this.size = value.size;
        this.publicationId = value.publicationId;
    }

    public PublicationVideoEntity(
        UUID   id,
        String extension,
        Long   size,
        UUID   publicationId
    ) {
        this.id = id;
        this.extension = extension;
        this.size = size;
        this.publicationId = publicationId;
    }

    /**
     * Getter for <code>public.publication_video.id</code>.
     */
    public UUID getId() {
        return this.id;
    }

    /**
     * Setter for <code>public.publication_video.id</code>.
     */
    public void setId(UUID id) {
        this.id = id;
    }

    /**
     * Getter for <code>public.publication_video.extension</code>.
     */
    public String getExtension() {
        return this.extension;
    }

    /**
     * Setter for <code>public.publication_video.extension</code>.
     */
    public void setExtension(String extension) {
        this.extension = extension;
    }

    /**
     * Getter for <code>public.publication_video.size</code>.
     */
    public Long getSize() {
        return this.size;
    }

    /**
     * Setter for <code>public.publication_video.size</code>.
     */
    public void setSize(Long size) {
        this.size = size;
    }

    /**
     * Getter for <code>public.publication_video.publication_id</code>.
     */
    public UUID getPublicationId() {
        return this.publicationId;
    }

    /**
     * Setter for <code>public.publication_video.publication_id</code>.
     */
    public void setPublicationId(UUID publicationId) {
        this.publicationId = publicationId;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("PublicationVideoEntity (");

        sb.append(id);
        sb.append(", ").append(extension);
        sb.append(", ").append(size);
        sb.append(", ").append(publicationId);

        sb.append(")");
        return sb.toString();
    }
}
