/*
 * This file is generated by jOOQ.
 */
package com.technokratos.model.jooq.tables.pojos;


import com.technokratos.model.jooq.enums.PublicationType;
import lombok.Builder;
import lombok.EqualsAndHashCode;

import java.io.Serializable;
import java.time.LocalDateTime;
import java.util.UUID;


/**
 * This class is generated by jOOQ.
 */
@Builder
@EqualsAndHashCode
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PublicationEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    private UUID            id;
    private String          description;
    private PublicationType type;
    private UUID            accountId;
    private LocalDateTime   createdDate;
    private LocalDateTime   updatedDate;

    public PublicationEntity() {}

    public PublicationEntity(PublicationEntity value) {
        this.id = value.id;
        this.description = value.description;
        this.type = value.type;
        this.accountId = value.accountId;
        this.createdDate = value.createdDate;
        this.updatedDate = value.updatedDate;
    }

    public PublicationEntity(
        UUID            id,
        String          description,
        PublicationType type,
        UUID            accountId,
        LocalDateTime   createdDate,
        LocalDateTime   updatedDate
    ) {
        this.id = id;
        this.description = description;
        this.type = type;
        this.accountId = accountId;
        this.createdDate = createdDate;
        this.updatedDate = updatedDate;
    }

    /**
     * Getter for <code>public.publication.id</code>.
     */
    public UUID getId() {
        return this.id;
    }

    /**
     * Setter for <code>public.publication.id</code>.
     */
    public void setId(UUID id) {
        this.id = id;
    }

    /**
     * Getter for <code>public.publication.description</code>.
     */
    public String getDescription() {
        return this.description;
    }

    /**
     * Setter for <code>public.publication.description</code>.
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * Getter for <code>public.publication.type</code>.
     */
    public PublicationType getType() {
        return this.type;
    }

    /**
     * Setter for <code>public.publication.type</code>.
     */
    public void setType(PublicationType type) {
        this.type = type;
    }

    /**
     * Getter for <code>public.publication.account_id</code>.
     */
    public UUID getAccountId() {
        return this.accountId;
    }

    /**
     * Setter for <code>public.publication.account_id</code>.
     */
    public void setAccountId(UUID accountId) {
        this.accountId = accountId;
    }

    /**
     * Getter for <code>public.publication.created_date</code>.
     */
    public LocalDateTime getCreatedDate() {
        return this.createdDate;
    }

    /**
     * Setter for <code>public.publication.created_date</code>.
     */
    public void setCreatedDate(LocalDateTime createdDate) {
        this.createdDate = createdDate;
    }

    /**
     * Getter for <code>public.publication.updated_date</code>.
     */
    public LocalDateTime getUpdatedDate() {
        return this.updatedDate;
    }

    /**
     * Setter for <code>public.publication.updated_date</code>.
     */
    public void setUpdatedDate(LocalDateTime updatedDate) {
        this.updatedDate = updatedDate;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("PublicationEntity (");

        sb.append(id);
        sb.append(", ").append(description);
        sb.append(", ").append(type);
        sb.append(", ").append(accountId);
        sb.append(", ").append(createdDate);
        sb.append(", ").append(updatedDate);

        sb.append(")");
        return sb.toString();
    }
}
