/*
 * This file is generated by jOOQ.
 */
package com.technokratos.model.jooq.tables.pojos;


import lombok.Builder;
import lombok.EqualsAndHashCode;

import java.io.Serializable;
import java.util.UUID;


/**
 * This class is generated by jOOQ.
 */
@Builder
@EqualsAndHashCode
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SubscriberSubscriptionEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    private UUID subscriberId;
    private UUID subscriptionId;

    public SubscriberSubscriptionEntity() {}

    public SubscriberSubscriptionEntity(SubscriberSubscriptionEntity value) {
        this.subscriberId = value.subscriberId;
        this.subscriptionId = value.subscriptionId;
    }

    public SubscriberSubscriptionEntity(
        UUID subscriberId,
        UUID subscriptionId
    ) {
        this.subscriberId = subscriberId;
        this.subscriptionId = subscriptionId;
    }

    /**
     * Getter for <code>public.subscriber_subscription.subscriber_id</code>.
     */
    public UUID getSubscriberId() {
        return this.subscriberId;
    }

    /**
     * Setter for <code>public.subscriber_subscription.subscriber_id</code>.
     */
    public void setSubscriberId(UUID subscriberId) {
        this.subscriberId = subscriberId;
    }

    /**
     * Getter for <code>public.subscriber_subscription.subscription_id</code>.
     */
    public UUID getSubscriptionId() {
        return this.subscriptionId;
    }

    /**
     * Setter for <code>public.subscriber_subscription.subscription_id</code>.
     */
    public void setSubscriptionId(UUID subscriptionId) {
        this.subscriptionId = subscriptionId;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("SubscriberSubscriptionEntity (");

        sb.append(subscriberId);
        sb.append(", ").append(subscriptionId);

        sb.append(")");
        return sb.toString();
    }
}
