/*
 * This file is generated by jOOQ.
 */
package com.technokratos.model.jooq.enums;


import com.technokratos.model.jooq.Public;

import org.jooq.Catalog;
import org.jooq.EnumType;
import org.jooq.Schema;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public enum Gender implements EnumType {

    MALE("MALE"),

    FEMALE("FEMALE");

    private final String literal;

    private Gender(String literal) {
        this.literal = literal;
    }

    @Override
    public Catalog getCatalog() {
        return getSchema().getCatalog();
    }

    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    @Override
    public String getName() {
        return "gender";
    }

    @Override
    public String getLiteral() {
        return literal;
    }
}
