/*
 * This file is generated by jOOQ.
 */
package com.technokratos.model.jooq.tables.records;


import com.technokratos.model.jooq.enums.AccountRole;
import com.technokratos.model.jooq.enums.AccountState;
import com.technokratos.model.jooq.enums.Gender;
import com.technokratos.model.jooq.tables.Account;

import java.time.LocalDateTime;
import java.util.UUID;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record13;
import org.jooq.Row13;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AccountRecord extends UpdatableRecordImpl<AccountRecord> implements Record13<UUID, String, String, String, AccountState, AccountRole, String, String, Gender, String, LocalDateTime, LocalDateTime, LocalDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.account.id</code>.
     */
    public void setId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.account.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.account.email</code>.
     */
    public void setEmail(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.account.email</code>.
     */
    public String getEmail() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.account.hash_password</code>.
     */
    public void setHashPassword(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.account.hash_password</code>.
     */
    public String getHashPassword() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.account.username</code>.
     */
    public void setUsername(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.account.username</code>.
     */
    public String getUsername() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.account.state</code>.
     */
    public void setState(AccountState value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.account.state</code>.
     */
    public AccountState getState() {
        return (AccountState) get(4);
    }

    /**
     * Setter for <code>public.account.role</code>.
     */
    public void setRole(AccountRole value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.account.role</code>.
     */
    public AccountRole getRole() {
        return (AccountRole) get(5);
    }

    /**
     * Setter for <code>public.account.first_name</code>.
     */
    public void setFirstName(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.account.first_name</code>.
     */
    public String getFirstName() {
        return (String) get(6);
    }

    /**
     * Setter for <code>public.account.last_name</code>.
     */
    public void setLastName(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.account.last_name</code>.
     */
    public String getLastName() {
        return (String) get(7);
    }

    /**
     * Setter for <code>public.account.gender</code>.
     */
    public void setGender(Gender value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.account.gender</code>.
     */
    public Gender getGender() {
        return (Gender) get(8);
    }

    /**
     * Setter for <code>public.account.about_me</code>.
     */
    public void setAboutMe(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.account.about_me</code>.
     */
    public String getAboutMe() {
        return (String) get(9);
    }

    /**
     * Setter for <code>public.account.birth_date</code>.
     */
    public void setBirthDate(LocalDateTime value) {
        set(10, value);
    }

    /**
     * Getter for <code>public.account.birth_date</code>.
     */
    public LocalDateTime getBirthDate() {
        return (LocalDateTime) get(10);
    }

    /**
     * Setter for <code>public.account.created_date</code>.
     */
    public void setCreatedDate(LocalDateTime value) {
        set(11, value);
    }

    /**
     * Getter for <code>public.account.created_date</code>.
     */
    public LocalDateTime getCreatedDate() {
        return (LocalDateTime) get(11);
    }

    /**
     * Setter for <code>public.account.updated_date</code>.
     */
    public void setUpdatedDate(LocalDateTime value) {
        set(12, value);
    }

    /**
     * Getter for <code>public.account.updated_date</code>.
     */
    public LocalDateTime getUpdatedDate() {
        return (LocalDateTime) get(12);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record13 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row13<UUID, String, String, String, AccountState, AccountRole, String, String, Gender, String, LocalDateTime, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row13) super.fieldsRow();
    }

    @Override
    public Row13<UUID, String, String, String, AccountState, AccountRole, String, String, Gender, String, LocalDateTime, LocalDateTime, LocalDateTime> valuesRow() {
        return (Row13) super.valuesRow();
    }

    @Override
    public Field<UUID> field1() {
        return Account.ACCOUNT_ENTITY.ID;
    }

    @Override
    public Field<String> field2() {
        return Account.ACCOUNT_ENTITY.EMAIL;
    }

    @Override
    public Field<String> field3() {
        return Account.ACCOUNT_ENTITY.HASH_PASSWORD;
    }

    @Override
    public Field<String> field4() {
        return Account.ACCOUNT_ENTITY.USERNAME;
    }

    @Override
    public Field<AccountState> field5() {
        return Account.ACCOUNT_ENTITY.STATE;
    }

    @Override
    public Field<AccountRole> field6() {
        return Account.ACCOUNT_ENTITY.ROLE;
    }

    @Override
    public Field<String> field7() {
        return Account.ACCOUNT_ENTITY.FIRST_NAME;
    }

    @Override
    public Field<String> field8() {
        return Account.ACCOUNT_ENTITY.LAST_NAME;
    }

    @Override
    public Field<Gender> field9() {
        return Account.ACCOUNT_ENTITY.GENDER;
    }

    @Override
    public Field<String> field10() {
        return Account.ACCOUNT_ENTITY.ABOUT_ME;
    }

    @Override
    public Field<LocalDateTime> field11() {
        return Account.ACCOUNT_ENTITY.BIRTH_DATE;
    }

    @Override
    public Field<LocalDateTime> field12() {
        return Account.ACCOUNT_ENTITY.CREATED_DATE;
    }

    @Override
    public Field<LocalDateTime> field13() {
        return Account.ACCOUNT_ENTITY.UPDATED_DATE;
    }

    @Override
    public UUID component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getEmail();
    }

    @Override
    public String component3() {
        return getHashPassword();
    }

    @Override
    public String component4() {
        return getUsername();
    }

    @Override
    public AccountState component5() {
        return getState();
    }

    @Override
    public AccountRole component6() {
        return getRole();
    }

    @Override
    public String component7() {
        return getFirstName();
    }

    @Override
    public String component8() {
        return getLastName();
    }

    @Override
    public Gender component9() {
        return getGender();
    }

    @Override
    public String component10() {
        return getAboutMe();
    }

    @Override
    public LocalDateTime component11() {
        return getBirthDate();
    }

    @Override
    public LocalDateTime component12() {
        return getCreatedDate();
    }

    @Override
    public LocalDateTime component13() {
        return getUpdatedDate();
    }

    @Override
    public UUID value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getEmail();
    }

    @Override
    public String value3() {
        return getHashPassword();
    }

    @Override
    public String value4() {
        return getUsername();
    }

    @Override
    public AccountState value5() {
        return getState();
    }

    @Override
    public AccountRole value6() {
        return getRole();
    }

    @Override
    public String value7() {
        return getFirstName();
    }

    @Override
    public String value8() {
        return getLastName();
    }

    @Override
    public Gender value9() {
        return getGender();
    }

    @Override
    public String value10() {
        return getAboutMe();
    }

    @Override
    public LocalDateTime value11() {
        return getBirthDate();
    }

    @Override
    public LocalDateTime value12() {
        return getCreatedDate();
    }

    @Override
    public LocalDateTime value13() {
        return getUpdatedDate();
    }

    @Override
    public AccountRecord value1(UUID value) {
        setId(value);
        return this;
    }

    @Override
    public AccountRecord value2(String value) {
        setEmail(value);
        return this;
    }

    @Override
    public AccountRecord value3(String value) {
        setHashPassword(value);
        return this;
    }

    @Override
    public AccountRecord value4(String value) {
        setUsername(value);
        return this;
    }

    @Override
    public AccountRecord value5(AccountState value) {
        setState(value);
        return this;
    }

    @Override
    public AccountRecord value6(AccountRole value) {
        setRole(value);
        return this;
    }

    @Override
    public AccountRecord value7(String value) {
        setFirstName(value);
        return this;
    }

    @Override
    public AccountRecord value8(String value) {
        setLastName(value);
        return this;
    }

    @Override
    public AccountRecord value9(Gender value) {
        setGender(value);
        return this;
    }

    @Override
    public AccountRecord value10(String value) {
        setAboutMe(value);
        return this;
    }

    @Override
    public AccountRecord value11(LocalDateTime value) {
        setBirthDate(value);
        return this;
    }

    @Override
    public AccountRecord value12(LocalDateTime value) {
        setCreatedDate(value);
        return this;
    }

    @Override
    public AccountRecord value13(LocalDateTime value) {
        setUpdatedDate(value);
        return this;
    }

    @Override
    public AccountRecord values(UUID value1, String value2, String value3, String value4, AccountState value5, AccountRole value6, String value7, String value8, Gender value9, String value10, LocalDateTime value11, LocalDateTime value12, LocalDateTime value13) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AccountRecord
     */
    public AccountRecord() {
        super(Account.ACCOUNT_ENTITY);
    }

    /**
     * Create a detached, initialised AccountRecord
     */
    public AccountRecord(UUID id, String email, String hashPassword, String username, AccountState state, AccountRole role, String firstName, String lastName, Gender gender, String aboutMe, LocalDateTime birthDate, LocalDateTime createdDate, LocalDateTime updatedDate) {
        super(Account.ACCOUNT_ENTITY);

        setId(id);
        setEmail(email);
        setHashPassword(hashPassword);
        setUsername(username);
        setState(state);
        setRole(role);
        setFirstName(firstName);
        setLastName(lastName);
        setGender(gender);
        setAboutMe(aboutMe);
        setBirthDate(birthDate);
        setCreatedDate(createdDate);
        setUpdatedDate(updatedDate);
    }
}
