/*
 * This file is generated by jOOQ.
 */
package com.technokratos.model.jooq.tables.records;


import com.technokratos.model.jooq.enums.PublicationType;
import com.technokratos.model.jooq.tables.Publication;

import java.time.LocalDateTime;
import java.util.UUID;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PublicationRecord extends UpdatableRecordImpl<PublicationRecord> implements Record6<UUID, String, PublicationType, UUID, LocalDateTime, LocalDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.publication.id</code>.
     */
    public void setId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.publication.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.publication.description</code>.
     */
    public void setDescription(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.publication.description</code>.
     */
    public String getDescription() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.publication.type</code>.
     */
    public void setType(PublicationType value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.publication.type</code>.
     */
    public PublicationType getType() {
        return (PublicationType) get(2);
    }

    /**
     * Setter for <code>public.publication.account_id</code>.
     */
    public void setAccountId(UUID value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.publication.account_id</code>.
     */
    public UUID getAccountId() {
        return (UUID) get(3);
    }

    /**
     * Setter for <code>public.publication.created_date</code>.
     */
    public void setCreatedDate(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.publication.created_date</code>.
     */
    public LocalDateTime getCreatedDate() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>public.publication.updated_date</code>.
     */
    public void setUpdatedDate(LocalDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.publication.updated_date</code>.
     */
    public LocalDateTime getUpdatedDate() {
        return (LocalDateTime) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row6<UUID, String, PublicationType, UUID, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    @Override
    public Row6<UUID, String, PublicationType, UUID, LocalDateTime, LocalDateTime> valuesRow() {
        return (Row6) super.valuesRow();
    }

    @Override
    public Field<UUID> field1() {
        return Publication.PUBLICATION_ENTITY.ID;
    }

    @Override
    public Field<String> field2() {
        return Publication.PUBLICATION_ENTITY.DESCRIPTION;
    }

    @Override
    public Field<PublicationType> field3() {
        return Publication.PUBLICATION_ENTITY.TYPE;
    }

    @Override
    public Field<UUID> field4() {
        return Publication.PUBLICATION_ENTITY.ACCOUNT_ID;
    }

    @Override
    public Field<LocalDateTime> field5() {
        return Publication.PUBLICATION_ENTITY.CREATED_DATE;
    }

    @Override
    public Field<LocalDateTime> field6() {
        return Publication.PUBLICATION_ENTITY.UPDATED_DATE;
    }

    @Override
    public UUID component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getDescription();
    }

    @Override
    public PublicationType component3() {
        return getType();
    }

    @Override
    public UUID component4() {
        return getAccountId();
    }

    @Override
    public LocalDateTime component5() {
        return getCreatedDate();
    }

    @Override
    public LocalDateTime component6() {
        return getUpdatedDate();
    }

    @Override
    public UUID value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getDescription();
    }

    @Override
    public PublicationType value3() {
        return getType();
    }

    @Override
    public UUID value4() {
        return getAccountId();
    }

    @Override
    public LocalDateTime value5() {
        return getCreatedDate();
    }

    @Override
    public LocalDateTime value6() {
        return getUpdatedDate();
    }

    @Override
    public PublicationRecord value1(UUID value) {
        setId(value);
        return this;
    }

    @Override
    public PublicationRecord value2(String value) {
        setDescription(value);
        return this;
    }

    @Override
    public PublicationRecord value3(PublicationType value) {
        setType(value);
        return this;
    }

    @Override
    public PublicationRecord value4(UUID value) {
        setAccountId(value);
        return this;
    }

    @Override
    public PublicationRecord value5(LocalDateTime value) {
        setCreatedDate(value);
        return this;
    }

    @Override
    public PublicationRecord value6(LocalDateTime value) {
        setUpdatedDate(value);
        return this;
    }

    @Override
    public PublicationRecord values(UUID value1, String value2, PublicationType value3, UUID value4, LocalDateTime value5, LocalDateTime value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PublicationRecord
     */
    public PublicationRecord() {
        super(Publication.PUBLICATION_ENTITY);
    }

    /**
     * Create a detached, initialised PublicationRecord
     */
    public PublicationRecord(UUID id, String description, PublicationType type, UUID accountId, LocalDateTime createdDate, LocalDateTime updatedDate) {
        super(Publication.PUBLICATION_ENTITY);

        setId(id);
        setDescription(description);
        setType(type);
        setAccountId(accountId);
        setCreatedDate(createdDate);
        setUpdatedDate(updatedDate);
    }
}
