/*
 * This file is generated by jOOQ.
 */
package com.technokratos.model.jooq.tables.records;


import com.technokratos.model.jooq.tables.SubscriberSubscription;

import java.util.UUID;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SubscriberSubscriptionRecord extends UpdatableRecordImpl<SubscriberSubscriptionRecord> implements Record2<UUID, UUID> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.subscriber_subscription.subscriber_id</code>.
     */
    public void setSubscriberId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.subscriber_subscription.subscriber_id</code>.
     */
    public UUID getSubscriberId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.subscriber_subscription.subscription_id</code>.
     */
    public void setSubscriptionId(UUID value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.subscriber_subscription.subscription_id</code>.
     */
    public UUID getSubscriptionId() {
        return (UUID) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<UUID, UUID> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row2<UUID, UUID> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Row2<UUID, UUID> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    public Field<UUID> field1() {
        return SubscriberSubscription.SUBSCRIBER_SUBSCRIPTION_ENTITY.SUBSCRIBER_ID;
    }

    @Override
    public Field<UUID> field2() {
        return SubscriberSubscription.SUBSCRIBER_SUBSCRIPTION_ENTITY.SUBSCRIPTION_ID;
    }

    @Override
    public UUID component1() {
        return getSubscriberId();
    }

    @Override
    public UUID component2() {
        return getSubscriptionId();
    }

    @Override
    public UUID value1() {
        return getSubscriberId();
    }

    @Override
    public UUID value2() {
        return getSubscriptionId();
    }

    @Override
    public SubscriberSubscriptionRecord value1(UUID value) {
        setSubscriberId(value);
        return this;
    }

    @Override
    public SubscriberSubscriptionRecord value2(UUID value) {
        setSubscriptionId(value);
        return this;
    }

    @Override
    public SubscriberSubscriptionRecord values(UUID value1, UUID value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SubscriberSubscriptionRecord
     */
    public SubscriberSubscriptionRecord() {
        super(SubscriberSubscription.SUBSCRIBER_SUBSCRIPTION_ENTITY);
    }

    /**
     * Create a detached, initialised SubscriberSubscriptionRecord
     */
    public SubscriberSubscriptionRecord(UUID subscriberId, UUID subscriptionId) {
        super(SubscriberSubscription.SUBSCRIBER_SUBSCRIPTION_ENTITY);

        setSubscriberId(subscriberId);
        setSubscriptionId(subscriptionId);
    }
}
