/*
 * This file is generated by jOOQ.
 */
package com.technokratos.model.jooq;


import com.technokratos.model.jooq.tables.Account;
import com.technokratos.model.jooq.tables.AccountImage;
import com.technokratos.model.jooq.tables.Publication;
import com.technokratos.model.jooq.tables.PublicationImage;
import com.technokratos.model.jooq.tables.PublicationVideo;
import com.technokratos.model.jooq.tables.RefreshToken;
import com.technokratos.model.jooq.tables.SubscriberSubscription;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Sequence;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.account</code>.
     */
    public final Account ACCOUNT_ENTITY = Account.ACCOUNT_ENTITY;

    /**
     * The table <code>public.account_image</code>.
     */
    public final AccountImage ACCOUNT_IMAGE_ENTITY = AccountImage.ACCOUNT_IMAGE_ENTITY;

    /**
     * The table <code>public.publication</code>.
     */
    public final Publication PUBLICATION_ENTITY = Publication.PUBLICATION_ENTITY;

    /**
     * The table <code>public.publication_image</code>.
     */
    public final PublicationImage PUBLICATION_IMAGE_ENTITY = PublicationImage.PUBLICATION_IMAGE_ENTITY;

    /**
     * The table <code>public.publication_video</code>.
     */
    public final PublicationVideo PUBLICATION_VIDEO_ENTITY = PublicationVideo.PUBLICATION_VIDEO_ENTITY;

    /**
     * The table <code>public.refresh_token</code>.
     */
    public final RefreshToken REFRESH_TOKEN_ENTITY = RefreshToken.REFRESH_TOKEN_ENTITY;

    /**
     * The table <code>public.subscriber_subscription</code>.
     */
    public final SubscriberSubscription SUBSCRIBER_SUBSCRIPTION_ENTITY = SubscriberSubscription.SUBSCRIBER_SUBSCRIPTION_ENTITY;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Sequence<?>> getSequences() {
        return Arrays.<Sequence<?>>asList(
            Sequences.REFRESH_TOKEN_ID_SEQ);
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.<Table<?>>asList(
            Account.ACCOUNT_ENTITY,
            AccountImage.ACCOUNT_IMAGE_ENTITY,
            Publication.PUBLICATION_ENTITY,
            PublicationImage.PUBLICATION_IMAGE_ENTITY,
            PublicationVideo.PUBLICATION_VIDEO_ENTITY,
            RefreshToken.REFRESH_TOKEN_ENTITY,
            SubscriberSubscription.SUBSCRIBER_SUBSCRIPTION_ENTITY);
    }
}
